---
blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/slgoodrich/agents/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: Community Guidelines
    url: >-
      https://github.com/slgoodrich/agents/blob/main/.github/CODE_OF_CONDUCT.md
    about: Review our community standards and code of conduct
  - name: Contributing Guide
    url: >-
      https://github.com/slgoodrich/agents/blob/main/.github/CONTRIBUTING.md
    about: Learn how to contribute to the Product Management Toolkit
